name: Validate json
on: [push, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Detect mixed line endings
        run: |
          MIXED_FILES=$(git ls-files --eol -- . | grep -E 'w/mixed' | cut -c3-)
          if [ -n "$MIXED_FILES" ]; then
            echo "Found files with mixed line endings:"
            echo "$MIXED_FILES"
            exit 1
          else
            echo "Line endings are not mixed"
          fi
      - name: Validate JSON with Glob and Formats
        uses: ScratchAddons/validate-json-action@master
        with:
          schema: /Script/schema.json
          jsons: ./cloudSettings.json      
